MODEL:
  arch: 'wrn_s2m2'

DATA:
  dataset: 'mini'  # Options: 'mini', 'cub', 'tiered', 'cifar'
  batch_size_loader: 256

  enlarge: True
  num_workers: 4
  disable_random_resize: False
  jitter: False
  path: 'data'

EVAL:
  evaluate: True       # Enable evaluation.
  number_tasks: 1000   # Number of evaluation tasks.
  batch_size: 1000
  n_ways: 5
  n_query: 15          # Queries per class in the balanced setting.
  balanced: 'dirichlet' # Options: 'balanced' or 'dirichlet'
  alpha_dirichlet: 2
  model_tag: 'best'
  plt_metrics: ['accs']
  shots: [1, 5]
  used_set: 'test'
  fresh_start: False
